name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: |
          pwd
          ls -R

      - name: Print Message
        run: |
          echo "Merhaba Ufuk!"
          echo "GitHub Actions çalışıyor."
